W0701 01:55:36.162000 2797910 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] 
W0701 01:55:36.162000 2797910 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] *****************************************
W0701 01:55:36.162000 2797910 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0701 01:55:36.162000 2797910 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] *****************************************
2025/07/01 01:58:04 INFO mlflow.system_metrics.system_metrics_monitor: Started monitoring system metrics.
Exception in thread SystemMetricsMonitor:
Traceback (most recent call last):
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/system_metrics/metrics/gpu_monitor.py", line 51, in collect_metrics
    power_milliwatts = pynvml.nvmlDeviceGetPowerUsage(handle)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/pynvml.py", line 3160, in nvmlDeviceGetPowerUsage
    _nvmlCheckReturn(ret)
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/pynvml.py", line 1042, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/rome/r24.04/Miniconda3/24.7.1-0/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/software/rome/r24.04/Miniconda3/24.7.1-0/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/system_metrics/system_metrics_monitor.py", line 122, in monitor
    self.collect_metrics()
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/system_metrics/system_metrics_monitor.py", line 148, in collect_metrics
    monitor.collect_metrics()
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/system_metrics/metrics/gpu_monitor.py", line 57, in collect_metrics
    except pynvml.nvml.NVMLError as e:
           ^^^^^^^^^^^
AttributeError: module 'pynvml' has no attribute 'nvml'
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 897896 ON i8028 CANCELLED AT 2025-07-02T01:54:39 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 897896.1 ON i8028 CANCELLED AT 2025-07-02T01:54:39 DUE TO TIME LIMIT ***
