W0704 13:49:03.504000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] 
W0704 13:49:03.504000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] *****************************************
W0704 13:49:03.504000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0704 13:49:03.504000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py:793] *****************************************
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/src/LWT/func_train.py", line 654, in <module>
[rank0]:     main()
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/src/LWT/func_train.py", line 621, in main
[rank0]:     mlflow.log_metric("SW_value", val, step=round_idx)
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 923, in log_metric
[rank0]:     return MlflowClient().log_metric(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/tracking/client.py", line 1532, in log_metric
[rank0]:     return self._tracking_client.log_metric(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 583, in log_metric
[rank0]:     self.store.log_metric(run_id, metric)
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 407, in log_metric
[rank0]:     self._call_endpoint(LogMetric, req_body)
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 82, in _call_endpoint
[rank0]:     return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 379, in call_endpoint
[rank0]:     response = verify_rest_response(response, endpoint)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 249, in verify_rest_response
[rank0]:     raise RestException(json.loads(response.text))
[rank0]: mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.UndefinedTable) relation "runs" does not exist
[rank0]: LINE 2: FROM runs 
[rank0]:              ^

[rank0]: [SQL: SELECT runs.run_uuid AS runs_run_uuid, runs.name AS runs_name, runs.source_type AS runs_source_type, runs.source_name AS runs_source_name, runs.entry_point_name AS runs_entry_point_name, runs.user_id AS runs_user_id, runs.status AS runs_status, runs.start_time AS runs_start_time, runs.end_time AS runs_end_time, runs.deleted_time AS runs_deleted_time, runs.source_version AS runs_source_version, runs.lifecycle_stage AS runs_lifecycle_stage, runs.artifact_uri AS runs_artifact_uri, runs.experiment_id AS runs_experiment_id 
[rank0]: FROM runs 
[rank0]: WHERE runs.run_uuid = %(run_uuid_1)s]
[rank0]: [parameters: {'run_uuid_1': '8682ca2e07ed4adf8fad91abdafc8b1c'}]
[rank0]: (Background on this error at: https://sqlalche.me/e/20/f405)
[rank0]:[W704 20:18:20.858486465 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0704 20:18:34.061000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 117190 closing signal SIGTERM
W0704 20:18:34.065000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 117191 closing signal SIGTERM
W0704 20:18:34.068000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 117192 closing signal SIGTERM
E0704 20:18:35.198000 117163 universal-ner-py311/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 117189) of binary: /data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/bin/python3.12
Traceback (most recent call last):
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/horse/ws/irve354e-energy_llm_ner/super_weights/universal-ner-py311/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/LWT/func_train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-04_20:18:34
  host      : c109.capella.hpc.tu-dresden.de
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 117189)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: c109: task 0: Exited with exit code 1
